---
- name: Setup backends
  uri:
    url: "{{ vault_addr }}/v1{{ item.path }}"
    method: "{{ item.method }}"
    body: "{{ item.parameters | to_json }}"
    body_format: json
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
    status_code: 204
    validate_certs: false
    return_content: true
  with_items:
    - "{{ vault_secret_backends }}"
    - "{{ vault_system_backends }}"
    - "{{ vault_auth_backends }}"
    - "{{ vault_policies }}"
    - "{{ vault_customs }}"
  register: setup_backends
  failed_when:
    - (setup_backends.status != 400) and ("'path is already in use' not in setup_backends.json")
    - setup_backends.status != 204
  no_log: true
