---

- name: Count amount of gpg used to unsead Vault
  set_fact:
    vault_gpg_shares: "{{ vault_gpg_keys_array | length }}"

- name: init - Run initialization
  uri:
    url: "{{ vault_addr }}/v1/sys/init"
    body: "{ \"secret_shares\": {{ vault_gpg_shares }}, \"secret_threshold\": 2, \"pgp_keys\": {{ vault_gpg_keys_array | to_json }} }"
    body_format: json
    method: PUT
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    return_content: yes
    validate_certs: false
  register: vault_init_response

- set_fact:
    vault_keys: "{{ vault_init_response.json }}"

- name: init - Output vault unseal keys
  debug:
    msg: "{{ item }}"
  with_indexed_items:
    - "{{ vault_keys.keys_base64 }}"
  when:
    - vault_keys.keys_base64 is defined

- name: init - Output root token
  debug:
    msg: "{{ vault_keys.root_token }}"
  when:
    - vault_keys.root_token is defined

- debug:
    msg: "Initialization of Vault completed. Unseal Vault manually with the vault-tool.sh and run next Stage manually"
